export const Routes = {
  Index: '/',
  Dashboard: '/dashboard',
  Signin: '/account/signin',
  Signout: '/account/signout',
  Signup: '/account/signup',
  ForgotPassword: '/account/forgot-password',
  ResetPassword: '/account/reset-password',
  Results: '/results',
  Payment: '/payment',
  Administrator: '/administrator',
  Scenario: '/scenario',
  StatisticsTeachers: '/statistics-teachers',
  CuratorHome: '/curator-home',
};
