export const colNames = [
  '№',
  'ФИО ученика',
  'ФИО учителя',
  'Возраст',
  'Дата регистрации',
  'Дата начала действия',
  'Дата окончания действия',
  'Тариф',
  'Дата оплаты',
  'Статус',
  'Юр. адрес',
];

export const list = [
  {
    id: 1,
    studentName: 'Ростовский И.Н.',
    teacherName: 'Свичкарь А.А.',
    age: 9,
    registrationDate: '11/03/2021',
    startDateAction: '11/04/2021',
    endDateAction: '11/04/2021',
    tariff: 'Начальный',
    paymentDate: '11/04/2021',
    status: 'Новый',
    legalAddress: 'Москва, ул. Ленина, 3/43',
  },
  {
    id: 2,
    studentName: 'Самойленко И.Н.',
    teacherName: 'Свичкарь А.А.',
    age: 9,
    registrationDate: '11/03/2021',
    startDateAction: '11/04/2021',
    endDateAction: '11/04/2021',
    tariff: 'Начальный',
    paymentDate: '11/04/2021',
    status: 'Новый',
    legalAddress: 'Москва, ул. Ленина, 3/43',
  },
  {
    id: 3,
    studentName: 'Самойленко И.Н.',
    teacherName: 'Свичкарь А.А.',
    age: 9,
    registrationDate: '11/03/2021',
    startDateAction: '11/04/2021',
    endDateAction: '11/04/2021',
    tariff: 'Начальный',
    paymentDate: '11/04/2021',
    status: 'Новый',
    legalAddress: 'Москва, ул. Ленина, 3/43',
  },
  {
    id: 4,
    studentName: 'Самойленко И.Н.',
    teacherName: 'Свичкарь А.А.',
    age: 9,
    registrationDate: '11/03/2021',
    startDateAction: '11/04/2021',
    endDateAction: '11/04/2021',
    tariff: 'Начальный',
    paymentDate: '11/04/2021',
    status: 'Новый',
    legalAddress: 'Москва, ул. Ленина, 3/43',
  },
];
